import PDFModal from '@/components/PDFModal';
import Head from 'next/head'
import { useState } from 'react';
import { Button } from 'react-bootstrap';

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  function handleShowModal() {
    setShowModal(true);
  }

  function handleCloseModal() {
    setShowModal(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <>
        <div>
        <Button onClick={handleShowModal}>Open PDF</Button>
        <PDFModal show={showModal} handleClose={handleCloseModal} />
      </div>
        </>
      </div>
    </>
  )
}
